// 单选题模拟数据 type:1
export const singleQuestionData = [
  {
    type: 1,
    fraction: 1,
    title: '1（）是社会主义法制核心内容。',
    isCollect: false,
    answerList: [
      {value: 1, label: '依法治国', isChecked: false},
      {value: 2, label: '执法为民', isChecked: false},
      {value: 3, label: '党的领导', isChecked: false},
      {value: 4, label: '公平正义', isChecked: false},
    ],
    yourAnswer: '',
    answerTime: '',
    okAnswer: 1,
    allAnswerNum: 256,
    allAnswerCorrectRate: 86,
    fallibility: 2,
    analysis: '1就撒开到好久啊大叔的黑科技啊说的话就卡上的回家看撒',
    isShowQuestionAnalysis: false,
  },
  {
    type: 1,
    fraction: 1,
    title: '2（）是社会主义法制核心内容。',
    isCollect: false,
    answerList: [
      {value: 1, label: '依法治国', isChecked: false},
      {value: 2, label: '执法为民', isChecked: false},
      {value: 3, label: '党的领导', isChecked: false},
      {value: 4, label: '公平正义', isChecked: false},
    ],
    yourAnswer: '',
    answerTime: '',
    okAnswer: 2,
    allAnswerNum: 256,
    allAnswerCorrectRate: 86,
    fallibility: 3,
    analysis: '1就撒开到好久啊大叔的黑科技啊说的话就卡上的回家看撒1就撒开到好久啊大叔的黑科技啊说的话就卡上的回家看撒1就撒开到好久啊大叔的黑科技啊说的话就卡上的回家看撒',
    isShowQuestionAnalysis: false,
  },
  {
    type: 1,
    fraction: 2,
    title: '3（）是社会主义法制核心内容。',
    isCollect: false,
    answerList: [
      {value: 1, label: '依法s治国', isChecked: false},
      {value: 2, label: '执法为民', isChecked: false},
      {value: 3, label: '党的领s导', isChecked: false},
      {value: 4, label: '公平正义', isChecked: false},
    ],
    yourAnswer: '',
    answerTime: '',
    okAnswer: 3,
    allAnswerNum: 123,
    allAnswerCorrectRate: 90,
    fallibility: 4,
    analysis: '1就撒开到好久啊大叔的黑科技啊说的话就卡上的回家看撒1就撒开到好久啊大叔的黑科技啊说的话就卡上的回家看撒1就撒开到好久啊大叔的黑科技啊说的话就卡上的回家看撒',
    isShowQuestionAnalysis: false,
  },
  {
    type: 2,
    fraction: 2,
    title: '社会主义法制理念的基本内涵包括（）。',
    isCollect: false,
    answerList: [
      {value: 1, label: '依法治国', isChecked: false},
      {value: 2, label: '执法为民', isChecked: false},
      {value: 3, label: '党的领导', isChecked: false},
      {value: 4, label: '公平正义', isChecked: false},
    ],
    yourAnswer: [],
    answerTime: '',
    okAnswer: [1,2,3],
    allAnswerNum: 128,
    allAnswerCorrectRate: 93,
    fallibility: [2,3],
    analysis: '依法治国、执法为民、公平正义、服务大局、党的领导',
    isShowQuestionAnalysis: false,
  },
  {
    type: 2,
    fraction: 20,
    title: '社会主义法制理念的基本内涵包括（）。',
    isCollect: false,
    answerList: [
      {value: 1, label: '依法治国', isChecked: false},
      {value: 2, label: '执法为民', isChecked: false},
      {value: 3, label: '党的领导', isChecked: false},
      {value: 4, label: '公平正义', isChecked: false},
    ],
    yourAnswer: [],
    answerTime: '',
    okAnswer: [1,2],
    allAnswerNum: 128,
    allAnswerCorrectRate: 93,
    fallibility: [2,3],
    analysis: '依法治国、执法为民、公平正义、服务大局、党的领导',
    isShowQuestionAnalysis: false,
  },
]

// 多选题模拟数据 type:2
export const severalQuestionData = [
  {
    type: 2,
    fraction: 2,
    title: '社会主义法制理念的基本内涵包括（）。',
    isCollect: false,
    answerList: [
      {value: 1, label: '依法治国', isChecked: false},
      {value: 2, label: '执法为民', isChecked: false},
      {value: 3, label: '党的领导', isChecked: false},
      {value: 4, label: '公平正义', isChecked: false},
    ],
    yourAnswer: [],
    answerTime: '',
    okAnswer: [1,2,3],
    allAnswerNum: 128,
    allAnswerCorrectRate: 93,
    fallibility: [2,3],
    analysis: '依法治国、执法为民、公平正义、服务大局、党的领导',
    isShowQuestionAnalysis: false,
  },
  {
    type: 2,
    fraction: 20,
    title: '社会主义法制理念的基本内涵包括（）。',
    isCollect: false,
    answerList: [
      {value: 1, label: '依法治国', isChecked: false},
      {value: 2, label: '执法为民', isChecked: false},
      {value: 3, label: '党的领导', isChecked: false},
      {value: 4, label: '公平正义', isChecked: false},
    ],
    yourAnswer: [],
    answerTime: '',
    okAnswer: [1,2],
    allAnswerNum: 128,
    allAnswerCorrectRate: 93,
    fallibility: [2,3],
    analysis: '依法治国、执法为民、公平正义、服务大局、党的领导',
    isShowQuestionAnalysis: false,
  },
]